spring.application.name=sunosarkar
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sunosarkar
spring.datasource.username=root
spring.datasource.password=Soni@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=sunosarkar-secret-key-2024-very-long-and-secure-key-for-jwt-signing
jwt.expiration=86400000

#mailsender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=internx1507@gmail.com
spring.mail.password=lpqn wlpg oioi dqts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true